language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - "pushd wpilib; pip install -r testing-requirements.txt; popd"
# command to run tests
script:
  - wpilib/tests/run_tests.sh
git:
  depth: 200
notifications:
  irc:
    channels:
    - "chat.freenode.net#robotpy"
    use_notice: true
    skip_join: true
    on_success: change
