language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - "pushd wpilib; pip install -r testing-requirements.txt; popd"
# command to run tests
script:
  - wpilib/tests/run_tests.sh
git:
  depth: 200
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2fb1c026e64fdd70d27b
    on_success: change
    on_failure: always
    on_start: never
